services:
  peer1:
    container_name: peer1
    build: .
    ports:
      - "5000:5000/udp"
    command:
      [
        "dotnet",
        "TrabalhoP2P.dll",
        "5000",
        "knownPeers/knownPeers1_docker.txt",
        "tmp/peer1",
      ]
    volumes:
      - ./tmp/peer1:/app/tmp/peer1
      - ./knownPeers/knownPeers1_docker.txt:/app/knownPeers/knownPeers1_docker.txt
    networks:
      - p2p-network

  peer2:
    container_name: peer2
    build: .
    ports:
      - "5001:5001/udp"
    command:
      [
        "dotnet",
        "TrabalhoP2P.dll",
        "5001",
        "knownPeers/knownPeers2_docker.txt",
        "tmp/peer2",
      ]
    volumes:
      - ./tmp/peer2:/app/tmp/peer2
      - ./knownPeers/knownPeers2_docker.txt:/app/knownPeers/knownPeers2_docker.txt
    networks:
      - p2p-network

  peer3:
    container_name: peer3
    build: .
    ports:
      - "5002:5002/udp"
    command:
      [
        "dotnet",
        "TrabalhoP2P.dll",
        "5002",
        "knownPeers/knownPeers3_docker.txt",
        "tmp/peer3",
      ]
    volumes:
      - ./tmp/peer3:/app/tmp/peer3
      - ./knownPeers/knownPeers3_docker.txt:/app/knownPeers/knownPeers3_docker.txt
    networks:
      - p2p-network
  
  peer4:
    container_name: peer4
    build: .
    ports:
      - "5003:5003/udp"
    command:
      [
        "dotnet",
        "TrabalhoP2P.dll",
        "5003",
        "knownPeers/knownPeers4_docker.txt",
        "tmp/peer4",
      ]
    volumes:
      - ./tmp/peer4:/app/tmp/peer4
      - ./knownPeers/knownPeers4_docker.txt:/app/knownPeers/knownPeers4_docker.txt
    networks:
      - p2p-network

networks:
  p2p-network:
    driver: bridge
    name: p2p-network